//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Feedback = new HashSet<Feedback>();
            this.Feedback1 = new HashSet<Feedback>();
            this.Request = new HashSet<Request>();
            this.Request1 = new HashSet<Request>();
            this.Request2 = new HashSet<Request>();
            this.User_Projects = new HashSet<User_Projects>();
        }


        [Display(Name = "Name")]
        public int userID { get; set; }
        [MinLength(3)]
        [Display(Name = "Password")]
        [Required]
        public string user_password { get; set; }
        [Display(Name = "Name")]
        [Required]
        public string name { get; set; }
        public Nullable<int> No_Of_Delievered_Projects { get; set; }
        public Nullable<int> Profits_For_Companies { get; set; }
        [Display(Name = "expeirence Years")]
        public Nullable<int> expeirenceYears { get; set; }
        [MaxLength(11)]
        [MinLength(11)]
        public string phone { get; set; }
        [EmailAddress]
        [Display(Name = "Email")]
        [Required]
        public string email { get; set; }
        [Display(Name ="Photo")]
       
        public string img { get; set; }
        [Required]
        [Display(Name = "JOB Description")]
        public string job_Desc { get; set; }
        [Display(Name = "Job")]
        public Nullable<int> job_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback1 { get; set; }
        public virtual Job_Title Job_Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Projects> User_Projects { get; set; }
    }
}
